all:compile

server-compile:
	gcc server.c -o server

client-compile:
	gcc client.c -o client

compile:
	gcc server.c -o server
	gcc client.c -o client

server-clean:
	rm server

client-clean:
	rm client

clean:
	rm server
	rm client
